# Generated by Django 4.0.3 on 2022-03-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='car',
            new_name='car_id',
        ),
    ]
